// Report type definitions and mock data

export const mockReports = [
  {
    id: "report-001",
    candidate: "Alice Johnson",
    role: "Senior Software Engineer",
    completedAt: "2024-01-15T14:30:00Z",
    recommendation: "strong_hire",
    lifecycleStatus: "approved",
    overallScore: { score: 92, confidence: "high", explanation: "Exceptional technical depth and communication skills demonstrated throughout the interview." },
    jobFitScore: { score: 95, confidence: "high", explanation: "Perfectly aligned with role requirements and team culture." },
    technicalScore: { score: 88, confidence: "high", explanation: "Strong problem-solving abilities and deep technical knowledge in required technologies." },
    communicationScore: { score: 96, confidence: "high", explanation: "Clear articulation of ideas and excellent collaborative approach." },
    strengths: ["Problem Solving", "Technical Depth", "Communication", "Leadership Potential", "Cultural Fit"],
    weaknesses: [],
    redFlags: [],
    benchmarking: { percentileRank: 5, totalCandidates: 145, roleAverage: 72, historicalAverage: 68 },
    compliance: {
      interviewIntegrityScore: 98,
      monitoringEvents: { tabSwitches: 0, faceMissingCount: 0, audioSilenceDuration: 5, multipleVoicesDetected: false },
      biasDetectionStatus: "clear",
      dataBalanceConfidence: "high",
    },
    versionInfo: { version: "1.0.0", aiModelVersion: "gpt-4-turbo", generatedAt: "2024-01-15T15:00:00Z" },
    recommendationExplanation: "Alice demonstrates exceptional qualifications for the role with strong technical fundamentals and excellent soft skills. She shows clear potential for growth into leadership positions.",
    questionBreakdown: [
      {
        id: "q-001",
        questionText: "Describe your experience with system design and architecture decisions",
        score: 90,
        timeTaken: 120,
        confidence: "high",
        responseSummary: "Detailed experience with microservices architecture and scalability considerations",
        evaluation: "Candidate provided comprehensive examples of architecture decisions with clear reasoning",
        redFlags: [],
      },
      {
        id: "q-002",
        questionText: "How do you handle disagreements with team members?",
        score: 95,
        timeTaken: 85,
        confidence: "high",
        responseSummary: "Collaborative approach with focus on finding common ground and technical merit",
        evaluation: "Excellent demonstration of emotional intelligence and communication",
        redFlags: [],
      },
    ],
    privateNotes: [
      {
        id: "note-001",
        authorName: "Sarah Smith",
        createdAt: "2024-01-15T16:30:00Z",
        content: "Definitely move forward. She has the exact skill set we need and great communication.",
      },
    ],
    comments: [
      {
        id: "comment-001",
        authorName: "John Doe",
        authorRole: "hiring_manager",
        createdAt: "2024-01-16T09:00:00Z",
        content: "Impressed by her system design knowledge. Let's move forward with offer.",
      },
    ],
    reviews: [
      {
        reviewerName: "Sarah Smith",
        reviewerRole: "technical_lead",
        decision: "hire",
        notes: "Strong technical candidate with excellent communication",
        reviewedAt: "2024-01-16T10:00:00Z",
      },
    ],
    auditLog: [
      {
        id: "audit-001",
        action: "Report Generated",
        performedBy: "System",
        performedByRole: "ai",
        timestamp: "2024-01-15T15:00:00Z",
      },
      {
        id: "audit-002",
        action: "Reviewed and Approved",
        performedBy: "Sarah Smith",
        performedByRole: "technical_lead",
        timestamp: "2024-01-16T10:00:00Z",
      },
    ],
  },
  {
    id: "report-002",
    candidate: "Bob Wilson",
    role: "Product Manager",
    completedAt: "2024-01-14T11:00:00Z",
    recommendation: "hire",
    lifecycleStatus: "reviewed",
    overallScore: { score: 78, confidence: "medium", explanation: "Good product sense with some gaps in data analysis." },
    jobFitScore: { score: 82, confidence: "medium", explanation: "Good alignment with role but could strengthen technical understanding." },
    technicalScore: { score: 72, confidence: "medium", explanation: "Adequate technical knowledge for the role." },
    communicationScore: { score: 81, confidence: "high", explanation: "Clear communication and presentation skills." },
    strengths: ["Strategic Thinking", "Communication", "User Empathy", "Team Leadership"],
    weaknesses: ["Data Analysis", "Technical Depth"],
    redFlags: [],
    benchmarking: { percentileRank: 25, totalCandidates: 145, roleAverage: 72, historicalAverage: 68 },
    compliance: {
      interviewIntegrityScore: 95,
      monitoringEvents: { tabSwitches: 1, faceMissingCount: 0, audioSilenceDuration: 10, multipleVoicesDetected: false },
      biasDetectionStatus: "clear",
      dataBalanceConfidence: "medium",
    },
    versionInfo: { version: "1.0.0", aiModelVersion: "gpt-4-turbo", generatedAt: "2024-01-14T12:00:00Z" },
    recommendationExplanation: "Bob shows solid product thinking and communication skills. While technical depth could be stronger, his strategic approach and team skills make him a viable candidate.",
    questionBreakdown: [
      {
        id: "q-003",
        questionText: "Tell us about a product you've built from scratch",
        score: 75,
        timeTaken: 150,
        confidence: "medium",
        responseSummary: "Described a mobile app project with focus on user features",
        evaluation: "Good user focus but lacked depth in data-driven decision making",
        redFlags: ["Limited Analytics Discussion"],
      },
    ],
    privateNotes: [
      {
        id: "note-002",
        authorName: "Mike Johnson",
        createdAt: "2024-01-14T13:30:00Z",
        content: "Good PM but might need training on analytics. Could pair with data analyst.",
      },
    ],
    comments: [],
    reviews: [
      {
        reviewerName: "Mike Johnson",
        reviewerRole: "hiring_manager",
        decision: "schedule_human_interview",
        notes: "Move to human review for final decision",
        reviewedAt: "2024-01-15T11:00:00Z",
      },
    ],
    auditLog: [
      {
        id: "audit-003",
        action: "Report Generated",
        performedBy: "System",
        performedByRole: "ai",
        timestamp: "2024-01-14T12:00:00Z",
      },
    ],
  },
  {
    id: "report-003",
    candidate: "Carol Davis",
    role: "UX Designer",
    completedAt: "2024-01-10T16:45:00Z",
    recommendation: "borderline",
    lifecycleStatus: "draft",
    overallScore: { score: 65, confidence: "medium", explanation: "Mixed interview performance with strengths in design but concerns about process rigor." },
    jobFitScore: { score: 68, confidence: "medium", explanation: "Adequate fit with some skill gaps in collaboration." },
    technicalScore: { score: 62, confidence: "medium", explanation: "Design fundamentals present but needs growth in UX research." },
    communicationScore: { score: 68, confidence: "medium", explanation: "Clear communication of ideas with room for improvement." },
    strengths: ["Visual Design", "Creativity", "User Testing Concepts"],
    weaknesses: ["UX Research Methodology", "Stakeholder Management", "Design System Knowledge"],
    redFlags: ["Limited Accessibility Knowledge"],
    benchmarking: { percentileRank: 60, totalCandidates: 145, roleAverage: 72, historicalAverage: 68 },
    compliance: {
      interviewIntegrityScore: 92,
      monitoringEvents: { tabSwitches: 2, faceMissingCount: 1, audioSilenceDuration: 8, multipleVoicesDetected: false },
      biasDetectionStatus: "review_needed",
      dataBalanceConfidence: "medium",
    },
    versionInfo: { version: "1.0.0", aiModelVersion: "gpt-4-turbo", generatedAt: "2024-01-10T17:00:00Z" },
    recommendationExplanation: "Carol shows creative design ability but has gaps in UX fundamentals and accessibility knowledge. Could be viable with training, requires senior review.",
    questionBreakdown: [
      {
        id: "q-005",
        questionText: "Walk us through your UX research process",
        score: 55,
        timeTaken: 130,
        confidence: "medium",
        responseSummary: "Basic user interview approach but missing key research methodologies",
        evaluation: "Lacked mention of A/B testing, analytics interpretation, or user testing frameworks",
        redFlags: ["Research Gaps", "Limited Methodology Knowledge"],
      },
    ],
    privateNotes: [
      {
        id: "note-003",
        authorName: "Lisa Chen",
        createdAt: "2024-01-10T18:00:00Z",
        content: "Requires senior review. Good design sense but needs UX research training.",
      },
    ],
    comments: [],
    reviews: [],
    auditLog: [
      {
        id: "audit-005",
        action: "Report Generated",
        performedBy: "System",
        performedByRole: "ai",
        timestamp: "2024-01-10T17:00:00Z",
      },
    ],
  },
  {
    id: "report-004",
    candidate: "David Martinez",
    role: "DevOps Engineer",
    completedAt: "2024-01-09T13:15:00Z",
    recommendation: "no_hire",
    lifecycleStatus: "reviewed",
    overallScore: { score: 42, confidence: "high", explanation: "Significant gaps in required DevOps skills and cloud platform knowledge." },
    jobFitScore: { score: 38, confidence: "high", explanation: "Poor alignment with role requirements." },
    technicalScore: { score: 35, confidence: "high", explanation: "Insufficient DevOps and infrastructure knowledge." },
    communicationScore: { score: 52, confidence: "medium", explanation: "Adequate but struggled to articulate technical concepts." },
    strengths: ["Basic Linux Knowledge", "Willing to Learn"],
    weaknesses: ["Cloud Platform Experience", "Container Orchestration", "Infrastructure as Code", "CI/CD Pipeline Knowledge"],
    redFlags: ["No Production DevOps Experience", "Minimal Kubernetes Knowledge"],
    benchmarking: { percentileRank: 92, totalCandidates: 145, roleAverage: 72, historicalAverage: 68 },
    compliance: {
      interviewIntegrityScore: 88,
      monitoringEvents: { tabSwitches: 4, faceMissingCount: 2, audioSilenceDuration: 15, multipleVoicesDetected: false },
      biasDetectionStatus: "clear",
      dataBalanceConfidence: "high",
    },
    versionInfo: { version: "1.0.0", aiModelVersion: "gpt-4-turbo", generatedAt: "2024-01-09T14:00:00Z" },
    recommendationExplanation: "David lacks the necessary DevOps experience and cloud knowledge required for this role. Not recommended for this position.",
    questionBreakdown: [
      {
        id: "q-007",
        questionText: "Describe your experience with Kubernetes and container orchestration",
        score: 25,
        timeTaken: 120,
        confidence: "high",
        responseSummary: "Limited to basic Docker knowledge, no Kubernetes experience",
        evaluation: "Critical gap for DevOps role. Candidate unable to discuss container orchestration concepts.",
        redFlags: ["No K8s Experience", "Missing Core Skills"],
      },
    ],
    privateNotes: [
      {
        id: "note-004",
        authorName: "Tom Wilson",
        createdAt: "2024-01-09T15:00:00Z",
        content: "Not ready for this level. Should consider junior roles or training programs.",
      },
    ],
    comments: [
      {
        id: "comment-002",
        authorName: "Tom Wilson",
        authorRole: "technical_lead",
        createdAt: "2024-01-09T15:30:00Z",
        content: "Pass on this candidate. Skills gap too large.",
      },
    ],
    reviews: [
      {
        reviewerName: "Tom Wilson",
        reviewerRole: "technical_lead",
        decision: "rejected",
        notes: "Significant skill gaps. Not suitable for this role.",
        reviewedAt: "2024-01-09T15:30:00Z",
      },
    ],
    auditLog: [
      {
        id: "audit-007",
        action: "Report Generated",
        performedBy: "System",
        performedByRole: "ai",
        timestamp: "2024-01-09T14:00:00Z",
      },
      {
        id: "audit-008",
        action: "Rejected",
        performedBy: "Tom Wilson",
        performedByRole: "technical_lead",
        timestamp: "2024-01-09T15:30:00Z",
      },
    ],
  },
];
